# Default locale for UI strings
locale: "fr"

# Customize UI strings
ui-strings:
  # display-help:         "Display help"
  # copy-to-clipboard:    "Copy in the clipboard"
  # mail-to-message:      "Send by email"
  # mail-subject:         "Results"
  # mail-body:            "Hi,\n%s\nThanks."
  # mail-body-default:    "Here is my feedback:\n"
  # redo:                 "Redo"
  # ok:                   "Okay"
  contact-intro:        "Vos remarques : "
  # toggle-summary-style: "Toggle summary style"
  # attention:            "Attention"

# Website header
header:
  title:    "Démonstrateur pour l'implémentation de l'algorithme d'orientation COVID-19"
  logo:     "https://solidarites-sante.gouv.fr/IMG/siteon0.jpg"
  color:    "is-primary"
  subtitle: "Ce site sert de **documentation** et ne doit pas être utilisé pour vous tester.<br/>**Cas avec l'arbre optimisé**.<br/>Retour à la [documentation](/covid19-algorithme-orientation/)."

# Website footer
footer:
  text:    "Démonstrateur pour l'implémentation de l'algorithme d'orientation COVID-19"
  contact:  "mobilisation-covid@sante.gouv.fr"

# Allow users to send you emails with the summary?
mail-to: "mobilisation-covid@sante.gouv.fr"

sticky-help: ""
sticky-help-color: "is-danger"

# Display help along with questions by default?
display-help: true

# Display summary when done?
display-summary: true

# Display score information?
display-score: true

# Display each score?
display-score-details: true

# Only the score with the highest value?
display-score-top-result: true

# In a branch of the tree, should the target node be set depending on
# the updated value of conditional-score-outputs?
conditional-navigation: true

# FIXME: rappel des mesures d'hygiène
# Some text message to always display after the score results
display-unconditionally: "Restez chez vous au maximum en attendant que les symptômes disparaissent. Prenez votre température deux fois par jour. Rappel des mesures d’hygiène. Un dispositif national grand public de soutien psychologique au bénéfice des personnes qui en auraient besoin est accessible via le numéro vert: 0 800 130 000."

# Set initial variables to register scores.  Each entry of
# score-variables start with the name of the variable (you can pick
# up any yaml-acceptable name), then:
#
# (1) "display": what to display when detailed scores are displayed
# (2) "value": the initial value of the variable
# (3) "as-top-result-display": what to display when the variable is
#      the one with the highest score when the user is done.
score-variables:
  age_range:
    display: "Tranche d'âge"
    value: ""
  weight:
    display: "Poids (kgs)"
    value: 0
  height:
    display: "Taille (centimètres)"
    value: 0
  fever:
    display: "Fièvre"
    value: "Non"
  temperature:
    display: "Température"
    value: "NSP"
  cough:
    display: "Toux"
    value: false
  agueusia_anosmia:
    display: "Trouble goût/odorat"
    value: false
  sore_throat_aches:
    display: "Douleurs"
    value: false
  diarrhea:
    display: "Diarrhées"
    value: false
  minor-severity-factors:
    display: "Facteurs de gravité mineurs"
    value: 0
  major-severity-factors:
    display: "Facteurs de gravité majeurs"
    value: 0
  pronostic-factors:
    display: "Facteurs pronostiques"
    value: 0

# Sync with pseudo-code.org:
# Priority 1 -> orientation_moins_de_15_ans
# Priority 6 -> orientation_domicile_surveillance_1
# Priority 4 -> orientation_consultation_surveillance_1
# Priority 3 -> orientation_consultation_surveillance_2
# Priority 2 -> orientation_SAMU
# Priority 7 -> orientation_consultation_surveillance_3
# Priority 5 -> orientation_consultation_surveillance_4
# Priority 8 -> orientation_surveillance
#
# Set conditional output depending on scores.
# Each entry is composed of the name of the condition (you can pick up
# any yaml-acceptable name), then:
#
# (1) notification (optional): bulma-based class names for the UI notification
# (2) message (mandatory): message to display when one of the condition is met
# (3) anything else is a "condition", which lists variables and their minimal
# values for the condition to be met.
conditional-score-outputs:
  orientation_moins_de_15_ans:
    priority: 1
    node: "fin-moins-de-15-ans"
    message: "Cette application n’est pas faite pour les personnes de moins de 15 ans.<br/>Prenez contact avec votre médecin généraliste au moindre doute.<br/>En cas d’urgence, appelez le [15](tel:15)."
    notification: "is-danger"
  orientation_SAMU:
    priority: 2
    sticky-help: "Appelez le [15](tel:15).  Si vous en avez la possibilité, merci de continuer à remplir le questionnaire jusqu’au bout."
    message: "Appelez le [15](tel:15)."
    notification: "is-danger"
  orientation_consultation_surveillance_2:
    priority: 3
    message: "Votre situation peut relever d’un COVID 19. Demandez une téléconsultation ou un médecin généraliste ou une visite à domicile. Si vous n'arrivez pas à obtenir de consultation, appelez le [15](tel:16)."
    notification: "is-danger"
  orientation_consultation_surveillance_1:
    priority: 4
    notification: "is-warning"
    message: "Votre situation peut relever d’un COVID 19. Demandez une téléconsultation ou un médecin généraliste ou une visite à domicile. Appelez le [15](tel:15) si une gêne respiratoire ou des difficultés importantes pour vous alimenter ou boire apparaissent pendant plus de 24 heures."
  orientation_consultation_surveillance_4:
    priority: 5
    notification: "is-warning"
    message: "Votre situation peut relever d’un COVID 19. Un avis médical est recommandé. Au moindre doute, appelez le [15](tel:15). Nous vous conseillons de rester à votre domicile."
  orientation_domicile_surveillance_1:
    priority: 6
    message: "Votre situation peut relever d’un COVID 19 qu’il faut surveiller. Si de nouveaux symptômes apparaissent, refaites le test ou consultez votre médecin. Nous vous conseillons de rester à votre domicile."
    notification: "is-warning"
  orientation_consultation_surveillance_3:
    priority: 7
    notification: "is-warning"
    message: "Votre situation peut relever d’un COVID 19. Demandez une téléconsultation ou un médecin généraliste ou une visite à domicile (SOS médecins, etc.)."
  orientation_surveillance:
    priority: 8
    notification: "is-success"
    message: "Votre situation ne relève probablement pas du COVID 19. N’hésitez pas à contacter votre médecin en cas de doute. Vous pouvez refaire le test en cas de nouveau symptôme pour réévaluer la situation. Pour toute information concernant le COVID 19, composer le 0 800 130 000."

# Mandatory configuration option
# FIXME: complete documentation
tree:
  - node:       "0"
    text:       "COVID19: Algorithme d'orientation - site de démonstration"
    home-page:  true
    force-help: true
    help:       "**Pour l'implémentation**: le premier écran doit donner les explications indispensable sur le questionnaire, son usage et ses limites."
    choices:
    - answer: "Démarrer"
      goto:   "1.1"

  - node:    "1.1"
    start-page: true
    text:    "Quel est votre âge ?"
    help: "**Pour l'implémentation:** quand l'âge est inférieur à 15 ans, aucune donnée ne doit être collectée et la personne doit être redirigée toute de suite vers un message de sortie."
    choices:
    - answer:  "Moins de 15 ans"
      score:
        age_range:
          value: "inf_15"
      goto:
        conditional-score-outputs: true
        default: "1.2"
    - answer:  "Entre 15 et 49 ans"
      goto:    "1.2"
    - answer:  "Entre 50 et 69 ans"
      score:
        age_range:
          value: "from_15_to_49"
      goto:    "1.2"
    - answer:  "70 ans ou plus"
      goto:    "1.2"
      score:
        pronostic-factors:
          value: 1
        age_range:
          value: "sup_70"

  - node:    "1.2"
    start-page: true
    progress:   "[1 21]"
    text:    "Êtes-vous dans l'impossibilité de vous alimenter ou boire DEPUIS 24 HEURES OU PLUS ?"
    help: "**Pour l'implémentation:** il s'agit ici de tester le premier facteur de gravité majeur."
    choices:
    - answer:  "Oui"
      score:
        major-severity-factors:
          value: 1
      goto:
        conditional-score-outputs: true
        default: "1.2bis"
    - answer:  "Non"
      goto: "1.2bis"

  - node:    "1.2bis"
    start-page: true
    progress:   "[2 21]"
    text:    "Dans les dernières 24 heures, avez-vous noté un manque de souffle INHABITUEL lorsque vous parlez ou faites un petit effort ?"
    help: "**Pour l'implémentation:** il s'agit ici de tester le deuxième facteur de gravité majeur."
    choices:
    - answer:  "Oui"
      score:
        major-severity-factors:
          value: 1
      goto:
        conditional-score-outputs: true
        default: "1.3"
    - answer:  "Non"
      goto: "1.3"

  - node:       "1.3"
    progress:   "[3 21]"
    text:       "Pensez-vous avoir eu de la fièvre ces derniers jours (frissons, sueurs) ?"
    start-page: true
    choices:
    - answer:  "Oui"
      score:
        fever:
          value: "Oui"
      goto:    "1.3bis"
    - answer:  "Non"
      goto:    "1.4"
    - answer:  "Je ne sais pas"
      goto:    "1.4"
      score:
        fever:
          value: "NSP"

  - node:       "1.3bis"
    progress:   "[4 21]"
    text:       "Quelle a été votre température la plus élevée ces dernières 48 heures ?"
    choices:
    - answer:  "**Inférieure** ou égale à 35,4°C"
      score:
        temperature:
          value: "inf_35.5"
        minor-severity-factors:
          value: 1
      goto:    "1.4"
    - answer:  "Entre 35,5 et 37,7°C"
      score:
        temperature:
          value: "35.5-37.7"
      goto:    "1.4"
    - answer:  "Entre 37,8 et 38,9°C"
      score:
        temperature:
          value: "37.8-38.9"
      goto:    "1.4"
    - answer:  "**Supérieure** ou égale à 39°C"
      score:
        minor-severity-factors:
          value: 1
      goto:    "1.4"
    - answer:  "Je ne sais pas"
      color: "is-warning"
      score:
        minor-severity-factors:
          value: 1
      goto:    "1.4"

  - node:    "1.4"
    progress:   "[5 21]"
    text:    "Avez-vous une fatigue inhabituelle ces derniers jours ?"
    choices:
    - answer:  "Oui"
      goto:    "1.4.1"
    - answer:  "Non"
      goto:    "1.5"

  - node:    "1.4.1"
    progress:   "[5 21]"
    text:    "Cette fatigue vous oblige-t-elle à vous reposer plus de la moitié de la journée ?"
    choices:
    - answer:  "Oui"
      score:
        minor-severity-factors:
          value: 1
      goto:    "1.5"
    - answer:  "Non"
      goto:    "1.5"

  - node:    "1.5"
    progress:   "[6 21]"
    text:    "Avez-vous une toux ou une augmentation de votre toux habituelle ces derniers jours ?"
    choices:
    - answer:  "Oui"
      score:
        cough:
          value: true
      goto:    "1.6"
    - answer:  "Non"
      goto:    "1.6"

  - node:      "1.6"
    progress:   "[7 21]"
    text:      "Avez-vous noté une forte diminution de votre goût ou de votre odorat ces derniers jours ?"
    choices:
    - answer:  "Oui"
      goto:    "1.7"
      score:
        agueusia_anosmia:
          value: true
    - answer:  "Non"
      goto:    "1.7"

  - node:    "1.7"
    progress:   "[8 21]"
    text:    "Avez-vous un mal de gorge ou des douleurs musculaires ou des courbatures inhabituelles ces derniers jours ?"
    choices:
    - answer:  "Oui"
      score:
        sore_throat_aches:
          value: true
      goto:    "1.8"
    - answer:  "Non"
      goto:    "1.8"

  - node:    "1.8"
    progress:   "[9 21]"
    text:    "Avez-vous de la diarrhée ces dernières 24 heures (au moins 3 selles molles) ?"
    choices:
    - answer:  "Oui"
      score:
        diarrhea:
          value: true
      goto:    "2.2"
    - answer:  "Non"
      goto:    "2.2"

  - node:    "2.2"
    progress:   "[10 21]"
    text:    "Quel est votre poids en kilogrammes ?"
    help: "**Pour l'implémentation:** demandez la saisie du poids exact."
    choices:
    - answer:  "<60"
      goto:    "2.3"
      score:
        weight:
          value: 60
    - answer:  "60-70"
      goto:    "2.3"
      score:
        weight:
          value: 70
    - answer:  "70-80"
      goto:    "2.3"
      score:
        weight:
          value: 80
    - answer:  "80-90"
      goto:    "2.3"
      score:
        weight:
          value: 90
    - answer:  "90-100"
      goto:    "2.3"
      score:
        weight:
          value: 100
    - answer:  "Plus de 100"
      goto:    "2.3"
      score:
        weight:
          value: 110

  - node:    "2.3"
    progress:   "[11 21]"
    text:    "Quelle est votre taille ?"
    help: "**Pour l'implémentation:** demandez la saisie de la taille exacte en centimètres."
    choices:
    - answer:  "<1m50"
      goto:    "2.4"
      score:
        height:
          value: 140
    - answer:  "1m50-1m60"
      goto:    "2.4"
      score:
        height:
          value: 150
    - answer:  "1m60-1m70"
      goto:    "2.4"
      score:
        height:
          value: 160
    - answer:  "1m70-1m80"
      goto:    "2.4"
      score:
        height:
          value: 170
    - answer:  "1m80-1m90"
      goto:    "2.4"
      score:
        height:
          value: 180
    - answer:  "Plus de 1m90"
      goto:    "2.4"
      score:
        height:
          value: 190

  - node:    "2.4"
    progress:   "[12 21]"
    help: "**Pour l'implémentation:** vous pouvez utiliser une case à cocher."
    text:    "Avez-vous une hypertension artérielle mal équilibrée ? Ou une maladie cardiaque ou vasculaire ? Ou prenez-vous un traitement à visée cardiologique ?"
    choices:
    - answer:  "Oui"
      goto:    "2.5"
      score:
        pronostic-factors:
          value: 1
    - answer:  "Non"
      goto:    "2.5"
    - answer:  "Je ne sais pas"
      color: "is-warning"
      goto:    "2.5"
      score:
        pronostic-factors:
          value: 1

  - node:    "2.5"
    progress:   "[13 21]"
    help: "**Pour l'implémentation:** vous pouvez utiliser une case à cocher."
    text:    "Êtes-vous diabétique ?"
    choices:
    - answer:  "Oui"
      goto:    "2.6"
      score:
        pronostic-factors:
          value: 1
    - answer:  "Non"
      goto:    "2.6"

  - node:    "2.6"
    progress:   "[14 21]"
    help: "**Pour l'implémentation:** vous pouvez utiliser une case à cocher."
    text:    "Avez-vous ou avez-vous eu un cancer dans les 3 dernières années ?"
    choices:
    - answer:  "Oui"
      goto:    "2.7"
      score:
        pronostic-factors:
          value: 1
    - answer:  "Non"
      goto:    "2.7"

  - node:    "2.7"
    progress:   "[15 21]"
    help: "**Pour l'implémentation:** vous pouvez utiliser une case à cocher."
    text:    "Avez-vous une maladie respiratoire ? Ou êtes-vous suivi par un pneumologue ?"
    choices:
    - answer:  "Oui"
      goto:    "2.8"
      score:
        pronostic-factors:
          value: 1
    - answer:  "Non"
      goto:    "2.8"

  - node:    "2.8"
    progress:   "[16 21]"
    help: "**Pour l'implémentation:** vous pouvez utiliser une case à cocher."
    text:    "Avez-vous une insuffisance rénale chronique dialysée ?"
    choices:
    - answer:  "Oui"
      goto:    "2.9"
      score:
        pronostic-factors:
          value: 1
    - answer:  "Non"
      goto:    "2.9"

  - node:    "2.9"
    progress:   "[17 21]"
    help: "**Pour l'implémentation:** vous pouvez utiliser une case à cocher."
    text:    "Avez-vous une maladie chronique du foie ?"
    choices:
    - answer:  "Oui"
      goto:    "2.10"
      score:
        pronostic-factors:
          value: 1
    - answer:  "Non"
      goto:    "2.10"

  - node:    "2.10"
    progress:   "[18 21]"
    help: "**Pour l'implémentation:** pas de case à cocher."
    text:    "Êtes-vous enceinte ?"
    choices:
    - answer:  "Oui"
      goto:    "2.11"
      score:
        pronostic-factors:
          value: 1
    - answer:  "Non"
      goto:    "2.11"
    - answer:  "Non applicable"
      color: "is-warning"
      goto:    "2.12"

  - node:    "2.11"
    progress:   "[19 21]"
    help: "**Pour l'implémentation:** si vous utilisez une case à cocher, ignorez la réponse \"Je ne sais pas\"."
    text:    "Avez-vous une maladie connue pour diminuer vos défenses immunitaires ?"
    choices:
    - answer:  "Oui"
      goto:    "2.12"
      score:
        pronostic-factors:
          value: 1
    - answer:  "Non"
      goto:    "2.12"
    - answer:  "Je ne sais pas"
      color: "is-warning"
      goto:    "2.12"

  - node:    "2.12"
    progress:   "[20 21]"
    help: "**Pour l'implémentation:** si vous utilisez une case à cocher, ignorez la réponse \"Je ne sais pas\"."
    text:    "Prenez-vous un traitement immunosuppresseur ?"
    help: "C’est un traitement qui diminue vos défenses contre les infections. Voici quelques exemples : corticoïdes, méthotrexate, ciclosporine, tacrolimus, azathioprine, cyclophosphamide (liste non exhaustive)."
    choices:
    - answer:  "Oui"
      goto:    "3.1"
      score:
        pronostic-factors:
          value: 1
    - answer:  "Non"
      goto:    "3.1"
    - answer:  "Je ne sais pas"
      color: "is-warning"
      goto:    "3.1"

  - node:    "3.1"
    progress:   "[21 21]"

    text:    "Quel est votre code postal ?"
    # help: "**Pour l'implémentation:** la saisie de cette information doit être facultative."
    choices:
    - answer:  "[Code postal]"
      goto:    "fin"

  - node: "fin-moins-de-15-ans"
    text: "Vous avez moins de quinze ans."
    done: true

  - node: "fin"
    text: "Merci d'avoir utilisé l'algorithme d'orientation COVID-19"
    help: "Cet algorithme est potentiellement modifiable après étude de cas et veille scientifique."
    done: true
